version: 2
jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: Build the docker image
          command: docker build -t xmr-stak:$CIRCLE_BRANCH .

      - run:
          name: Run a benchmark with Monero V8
          command: docker run --rm -t xmr-stak:$CIRCLE_BRANCH /usr/local/bin/xmr-stak --benchmark 8 --currency monero --httpd 0 --url pool.usxmrpool.com:3333 --user x --pass x --rigid x
